# Generated by Django 3.2 on 2021-06-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sex',
            field=models.CharField(blank=True, choices=[('FEMALE', '여성'), ('MALE', '남성')], default=None, max_length=30, null=True),
        ),
    ]
