# Generated by Django 3.2 on 2021-06-19 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='sex',
        ),
    ]
