# Generated by Django 3.2 on 2021-05-17 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_apply_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='sex',
            field=models.CharField(choices=[('FEMALE', '여성'), ('MALE', '남성')], max_length=30),
        ),
    ]
