# Generated by Django 3.2 on 2021-05-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_apply_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='image',
            field=models.ImageField(default='null', upload_to='post_img/'),
        ),
    ]
